name: temp1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  crystal_navigation_bar: ^1.0.0
  firebase_core: ^2.24.0


flutter:
  uses-material-design: true
  # assets:
    # - assets/images/

